export const theme = {
  bg: {
    base: "var(--bg-base)",
    surface: "var(--bg-surface)",
    raised: "var(--bg-raised)",
    prominent: "var(--bg-prominent)",
  },
  border: {
    primary: "var(--border-primary)",
    subtle: "var(--border-subtle)",
    divider: "var(--border-divider)",
  },
  text: {
    primary: "var(--text-primary)",
    secondary: "var(--text-secondary)",
    tertiary: "var(--text-tertiary)",
    muted: "var(--text-muted)",
  },
  accent: {
    timecode: "var(--accent-timecode)",
    primary: "var(--accent-primary)",
  },
  status: {
    error: "var(--status-error)",
  },
  track: {
    video: "var(--track-video)",
    audio: "var(--track-audio)",
    image: "var(--track-image)",
    text: "var(--track-text)",
    lottie: "var(--track-lottie)",
  },
  opacity: {
    subtle: "var(--opacity-subtle)",
    hint: "var(--opacity-hint)",
    faint: "var(--opacity-faint)",
    soft: "var(--opacity-soft)",
    muted: "var(--opacity-muted)",
    moderate: "var(--opacity-moderate)",
    medium: "var(--opacity-medium)",
    strong: "var(--opacity-strong)",
    prominent: "var(--opacity-prominent)",
    opaque: "var(--opacity-opaque)",
  },
  radius: {
    xs: "var(--radius-xs)",
    xsSm: "var(--radius-xs-sm)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    mdLg: "var(--radius-md-lg)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
  },
  spacing: {
    xxs: "var(--spacing-xxs)",
    xs: "var(--spacing-xs)",
    sm: "var(--spacing-sm)",
    smMd: "var(--spacing-sm-md)",
    md: "var(--spacing-md)",
    mdLg: "var(--spacing-md-lg)",
    lg: "var(--spacing-lg)",
    lgXl: "var(--spacing-lg-xl)",
    xl: "var(--spacing-xl)",
    xlXxl: "var(--spacing-xl-xxl)",
    xxl: "var(--spacing-xxl)",
  },
  fontSize: {
    micro: "var(--font-micro)",
    xxs: "var(--font-xxs)",
    xs: "var(--font-xs)",
    sm: "var(--font-sm)",
    smMd: "var(--font-sm-md)",
    md: "var(--font-md)",
    mdLg: "var(--font-md-lg)",
    lg: "var(--font-lg)",
    xl: "var(--font-xl)",
    title1: "var(--font-title1)",
    title2: "var(--font-title2)",
    display: "var(--font-display)",
  },
  borderWidth: {
    hairline: "var(--border-width-hairline)",
    thin: "var(--border-width-thin)",
    medium: "var(--border-width-medium)",
    thick: "var(--border-width-thick)",
  },
  fontWeight: {
    light: "var(--font-weight-light)",
    regular: "var(--font-weight-regular)",
    medium: "var(--font-weight-medium)",
    semibold: "var(--font-weight-semibold)",
    bold: "var(--font-weight-bold)",
  },
  iconSize: {
    lgXl: "var(--icon-size-lg-xl)",
  },
  size: {
    topBar: "var(--size-topbar)",
    resizeHandle: "var(--size-resize-handle)",
    transportPlay: "var(--size-transport-play)",
    overlayHandle: "var(--size-overlay-handle)",
  },
  overlay: {
    transformBorder: "var(--color-overlay-transform-border)",
    handleFill: "var(--color-overlay-handle-fill)",
    handleStroke: "var(--color-overlay-handle-stroke)",
    cropBorder: "var(--color-overlay-crop-border)",
    cropHandle: "var(--color-overlay-crop-handle)",
  },
} as const;

export type Theme = typeof theme;
