export const theme = {
  bg: {
    base: "var(--bg-base)",
    surface: "var(--bg-surface)",
    raised: "var(--bg-raised)",
    prominent: "var(--bg-prominent)",
    previewLetterbox: "var(--color-preview-letterbox)",
    scrim: "var(--color-scrim)",
  },
  border: {
    primary: "var(--border-primary)",
    subtle: "var(--border-subtle)",
    divider: "var(--border-divider)",
  },
  text: {
    primary: "var(--text-primary)",
    secondary: "var(--text-secondary)",
    tertiary: "var(--text-tertiary)",
    muted: "var(--text-muted)",
    onAccent: "var(--color-text-on-accent)",
  },
  accent: {
    timecode: "var(--accent-timecode)",
    primary: "var(--accent-primary)",
    glassTint: "var(--color-glass-tint)",
  },
  status: {
    error: "var(--status-error)",
    success: "var(--status-success)",
  },
  track: {
    video: "var(--track-video)",
    audio: "var(--track-audio)",
    image: "var(--track-image)",
    text: "var(--track-text)",
    lottie: "var(--track-lottie)",
  },
  opacity: {
    subtle: "var(--opacity-subtle)",
    hint: "var(--opacity-hint)",
    faint: "var(--opacity-faint)",
    soft: "var(--opacity-soft)",
    muted: "var(--opacity-muted)",
    moderate: "var(--opacity-moderate)",
    medium: "var(--opacity-medium)",
    disabled: "var(--opacity-disabled)",
    strong: "var(--opacity-strong)",
    prominent: "var(--opacity-prominent)",
    high: "var(--opacity-high)",
    opaque: "var(--opacity-opaque)",
  },
  opacityNum: {
    mixedFill: 0.3,
  },
  shadow: {
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
  },
  radius: {
    xs: "var(--radius-xs)",
    xsSm: "var(--radius-xs-sm)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    mdLg: "var(--radius-md-lg)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    pill: "var(--radius-pill)",
  },
  spacing: {
    xxs: "var(--spacing-xxs)",
    xs: "var(--spacing-xs)",
    sm: "var(--spacing-sm)",
    smMd: "var(--spacing-sm-md)",
    md: "var(--spacing-md)",
    mdLg: "var(--spacing-md-lg)",
    lg: "var(--spacing-lg)",
    lgXl: "var(--spacing-lg-xl)",
    xl: "var(--spacing-xl)",
    xlXxl: "var(--spacing-xl-xxl)",
    xxl: "var(--spacing-xxl)",
  },
  fontSize: {
    micro: "var(--font-micro)",
    xxs: "var(--font-xxs)",
    xs: "var(--font-xs)",
    sm: "var(--font-sm)",
    smMd: "var(--font-sm-md)",
    md: "var(--font-md)",
    mdLg: "var(--font-md-lg)",
    lg: "var(--font-lg)",
    xl: "var(--font-xl)",
    title1: "var(--font-title1)",
    title2: "var(--font-title2)",
    display: "var(--font-display)",
  },
  borderWidth: {
    hairline: "var(--border-width-hairline)",
    thin: "var(--border-width-thin)",
    medium: "var(--border-width-medium)",
    thick: "var(--border-width-thick)",
  },
  fontWeight: {
    light: "var(--font-weight-light)",
    regular: "var(--font-weight-regular)",
    medium: "var(--font-weight-medium)",
    semibold: "var(--font-weight-semibold)",
    bold: "var(--font-weight-bold)",
  },
  iconSize: {
    xxs: "var(--icon-size-xxs)",
    xs: "var(--icon-size-xs)",
    sm: "var(--icon-size-sm)",
    smMd: "var(--icon-size-sm-md)",
    md: "var(--icon-size-md)",
    mdLg: "var(--icon-size-md-lg)",
    lg: "var(--icon-size-lg)",
    lgXl: "var(--icon-size-lg-xl)",
    xl: "var(--icon-size-xl)",
  },
  letterSpacing: {
    tight: "var(--letter-spacing-tight)",
    wide: "var(--letter-spacing-wide)",
  },
  gradients: {
    ai: "var(--gradient-ai)",
    aiDark: "var(--gradient-ai-dark)",
  },
  size: {
    topBar: "var(--size-topbar)",
    resizeHandle: "var(--size-resize-handle)",
    transportPlay: "var(--size-transport-play)",
    overlayHandle: "var(--size-overlay-handle)",
    mediaItemMin: "var(--size-media-item-min)",
    mediaTabRail: "var(--size-media-tab-rail)",
    inspectorLabel: "var(--size-inspector-label)",
    inspectorValue: "var(--size-inspector-value)",
    kfLane: "var(--size-kf-lane)",
    kfDiamond: "var(--size-kf-diamond)",
    kfToggle: "var(--size-kf-toggle)",
    kfLabel: "var(--size-kf-label)",
    menuMin: "var(--size-menu-min)",
    dialogMin: "var(--size-dialog-min)",
    mentionPickerMax: "var(--size-mention-picker-max)",
    sessionListMax: "var(--size-session-list-max)",
    generationPanelMin: "var(--size-generation-panel-min)",
    settingsPanelMin: "var(--size-settings-panel-min)",
    activityMax: "var(--size-activity-max)",
    activityCost: "var(--size-activity-cost)",
    skillsPaneHeight: "var(--size-skills-pane-height)",
    skillsListWidth: "var(--size-skills-list-width)",
    skillsSpinner: "var(--size-skills-spinner)",
    skillsToastMax: "var(--size-skills-toast-max)",
    adjustTrack: "var(--size-adjust-track)",
    adjustThumb: "var(--size-adjust-thumb)",
    colorWheelPad: "var(--size-color-wheel-pad)",
    colorWheelPuck: "var(--size-color-wheel-puck)",
    curveCanvas: "var(--size-curve-canvas)",
    curveDot: "var(--size-curve-dot)",
    presetCardMin: "var(--size-preset-card-min)",
    presetPreviewHeight: "var(--size-preset-preview-height)",
    colorSwatch: "var(--size-color-swatch)",
    adjustLabelCol: "var(--size-adjust-label-col)",
    panelHeader: "var(--size-panel-header)",
    projectCardW: "var(--size-project-card-w)",
    projectCardH: "var(--size-project-card-h)",
    clipDetailMin: "var(--size-clip-detail-min)",
    clipLabelMin: "var(--size-clip-label-min)",
    captionPreviewMaxH: "var(--size-caption-preview-max-h)",
    toolImagePreviewMaxH: "var(--size-tool-image-preview-max-h)",
    genMediaAreaMinH: "var(--size-gen-media-area-min-h)",
    genLoadingH: "var(--size-gen-loading-h)",
    genPromptMinH: "var(--size-gen-prompt-min-h)",
    genRefTileW: "var(--size-gen-ref-tile-w)",
    genRefTileH: "var(--size-gen-ref-tile-h)",
    exportSheetW: "var(--size-export-sheet-w)",
    exportSheetH: "var(--size-export-sheet-h)",
    matteSheetW: "var(--size-matte-sheet-w)",
    matteControlW: "var(--size-matte-control-w)",
  },
  adjust: {
    tempCool: "var(--color-adjust-temp-cool)",
    tempWarm: "var(--color-adjust-temp-warm)",
    tintGreen: "var(--color-adjust-tint-green)",
    tintMagenta: "var(--color-adjust-tint-magenta)",
    lumaDark: "var(--color-adjust-luma-dark)",
    lumaLight: "var(--color-adjust-luma-light)",
    wheelRing: "var(--color-adjust-wheel-ring)",
    wheelCrosshair: "var(--color-adjust-wheel-crosshair)",
    wheelPuckFill: "var(--color-adjust-wheel-puck-fill)",
    wheelPuckStroke: "var(--color-adjust-wheel-puck-stroke)",
    curveGrid: "var(--color-adjust-curve-grid)",
    curveBorder: "var(--color-adjust-curve-border)",
    curveIdentity: "var(--color-adjust-curve-identity)",
    curveY: "var(--color-adjust-curve-y)",
    curveR: "var(--color-adjust-curve-r)",
    curveG: "var(--color-adjust-curve-g)",
    curveB: "var(--color-adjust-curve-b)",
    hueCurveNeutral: "var(--color-adjust-huecurve-neutral)",
    hueCurveHue: "var(--color-adjust-huecurve-hue)",
    hueCurveSat: "var(--color-adjust-huecurve-sat)",
    hueCurveLum: "var(--color-adjust-huecurve-lum)",
  },
  z: {
    menu: "var(--z-menu)",
    dialog: "var(--z-dialog)",
    dragGhost: "var(--z-drag-ghost)",
    toast: "var(--z-toast)",
  },
  overlay: {
    transformBorder: "var(--color-overlay-transform-border)",
    handleFill: "var(--color-overlay-handle-fill)",
    handleStroke: "var(--color-overlay-handle-stroke)",
    cropBorder: "var(--color-overlay-crop-border)",
    cropHandle: "var(--color-overlay-crop-handle)",
  },
  timeline: {
    trimHandle: "var(--color-timeline-trim-handle)",
    clipLabel: "var(--color-timeline-clip-label)",
    generatingScrim: "var(--color-timeline-generating-scrim)",
    failedScrim: "var(--color-timeline-failed-scrim)",
  },
  generating: {
    overlayBg: "var(--color-generating-overlay-bg)",
    track: "var(--color-generating-track)",
    fill: "var(--color-generating-fill)",
  },
  folder: {
    tileBg: "var(--color-folder-tile-bg)",
    icon: "var(--color-folder-icon)",
    badgeBg: "var(--color-folder-badge-bg)",
    badgeText: "var(--color-folder-badge-text)",
  },
  anim: {
    hover: "var(--anim-hover)",
    transition: "var(--anim-transition)",
    shimmerDuration: "var(--anim-shimmer-duration)",
    progressDuration: "var(--anim-progress-duration)",
    presetPreviewDuration: "var(--anim-preset-preview-duration)",
    presetPreviewSoloDuration: "var(--anim-preset-preview-solo-duration)",
  },
} as const;

export type Theme = typeof theme;
